version: '3.3'
services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: fiaphmv20
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  backendapp:
    image: thocorr/hmvbackend20:4
    container_name: backendapp
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    
volumes:
  db-data:
